query getBookmarksDocument($relativePath: String!) {
  getBookmarksDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...BookmarksParts
    }
  }
}

query getBookmarksList {
  getBookmarksList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...BookmarksParts
        }
      }
    }
  }
}
